<template>
  <div class="min-h-screen bg-blue-pale">
    <div class="max-w-4xl mx-auto px-4 py-12">
      <div class="mb-6">
        <NuxtLink to="/" class="flex items-center text-blue-navtext hover:text-blue-pricinghover transition-colors duration-200">
          <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back
        </NuxtLink>
      </div>

      <h1 class="text-4xl lg:text-5xl font-extrabold leading-tight mb-8 text-blue-h1">Disclaimer</h1>
      <p class="text-blue-footertext mb-8 text-lg">Last Updated: {{ new Date().toLocaleDateString() }}</p>
      
      <div class="space-y-6 text-blue-footertext leading-relaxed">
        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">1. General Information</h2>
          <p>The Midjourney Video Generator is an AI-powered video generation platform. This disclaimer outlines important information about our services and your use of our platform.</p>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">2. AI-Generated Content</h2>
          <p>The images created through our service are generated by artificial intelligence. While we strive for high quality, please understand:</p>
          <ul class="list-disc pl-6 mt-2">
            <li><strong class="text-blue-button">AI-generated content</strong> may contain imperfections or inaccuracies</li>
            <li><strong class="text-blue-button">Results vary</strong> based on the quality and specificity of prompts provided</li>
            <li>Generated images may unintentionally resemble existing content</li>
            <li>The same prompt may produce different results in different generations</li>
          </ul>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">3. Usage Limitations</h2>
          <p>The Midjourney Video Generator's services are provided "as is" without warranties of any kind. We do not guarantee:</p>
          <ul class="list-disc pl-6 mt-2">
            <li>Uninterrupted or error-free service</li>
            <li>Specific results or outcomes from using our image generation tools</li>
            <li>Appropriateness of generated content for all purposes</li>
            <li>Complete accuracy or adherence to all user specifications</li>
          </ul>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">4. Intellectual Property</h2>
          <p>While you retain rights to your generated images as outlined in our Terms of Service, please note:</p>
          <ul class="list-disc pl-6 mt-2">
            <li>Our AI models have been trained on diverse datasets</li>
            <li>Generated images may inadvertently bear similarity to existing works</li>
            <li><strong class="text-blue-button">Users are responsible</strong> for ensuring their use of generated images does not infringe on third-party rights</li>
            <li>The Midjourney Video Generator is not liable for intellectual property disputes arising from use of our services</li>
          </ul>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">5. Content Moderation</h2>
          <p>We implement content moderation systems, but they are not infallible:</p>
          <ul class="list-disc pl-6 mt-2">
            <li>Our systems may occasionally block legitimate content</li>
            <li>Users are responsible for complying with our content policies regardless of what our systems allow</li>
            <li>We reserve the right to remove any content at our discretion</li>
          </ul>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">6. Limitation of Liability</h2>
          <p>In no event shall The Midjourney Video Generator be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities arising out of your use of our services.</p>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">7. Service Changes</h2>
          <p>The Midjourney Video Generator reserves the right to modify, suspend, or discontinue any aspect of our service at any time, including the availability of any feature, database, or content.</p>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">8. Governing Law</h2>
          <p>This disclaimer and any disputes arising out of or related to your use of The Midjourney Video Generator shall be governed by the laws of the jurisdiction where The Midjourney Video Generator is registered, without regard to its conflict of law provisions.</p>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">9. Contact Information</h2>
          <p>For questions regarding this disclaimer, please contact us at: <strong class="text-blue-button">support@aimagen4.com</strong></p>
        </section>

        <section class="mt-8">
          <p class="text-sm">Last updated: {{ new Date().toLocaleDateString() }}</p>
        </section>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useSeo } from '~/composables/useSeo';

// @ts-ignore: Nuxt宏函数
definePageMeta({
  layout: false,
  name: 'disclaimer'
})

useSeo({
  title: 'The Midjourney Video Generator | Disclaimer',
  description: 'Read the disclaimer for The Midjourney Video Generator - important information about our AI video generation platform and your use of our services.'
})
</script>

<style>
/* 移除不必要的全局样式，使用tailwind类名代替 */
</style> 