<template>
  <div class="min-h-screen bg-banana-dark-bg text-banana-text-light font-['Inter']">
    <div class="max-w-4xl mx-auto px-4 py-12">
      <div class="mb-6">
        <NuxtLink to="/" class="flex items-center text-banana-text-muted hover:text-banana-primary-yellow transition-colors duration-200">
          <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back to Home
        </NuxtLink>
      </div>


      <div class="space-y-6 text-banana-text-muted leading-normal">
        <section>
          <h1 class="text-4xl lg:text-5xl font-extrabold leading-tight mb-8 text-banana-text-light">Terms of Service</h1>
      <p class="text-banana-text-muted mb-8 text-lg">Effective Date: August 29,2025</p>
      
          <h2 class="text-2xl font-bold mb-4 text-banana-primary-yellow">1. Acceptance of Terms</h2>
          <p>By accessing or using the MuseSteamer AI service ("Service"), you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access our Service.</p>

          <h2 class="text-2xl font-bold mt-8 mb-4 text-banana-primary-yellow">2. Service Description</h2>
          <p>MuseSteamer AI provides an advanced AI-powered platform for creative content generation, specializing in:</p>
          <ul class="list-disc pl-6 mt-4 space-y-2">
            <li><strong class="text-banana-text-light">Image-to-Video Generation</strong>: Creating dynamic videos from still images and textual descriptions.</li>
            <li><strong class="text-banana-text-light">AI-Powered Video Editing</strong>: Modifying existing videos using natural language commands and multimodal inputs.</li>
            <li><strong class="text-banana-text-light">Audio-Visual Integration</strong>: Generating videos with synchronized audio, including dialogue, sound effects, and ambient music.</li>
            <li><strong class="text-banana-text-light">High-Quality Output</strong>: Generating high-resolution videos suitable for various applications, from social media to professional productions.</li>
          </ul>

          <h2 class="text-2xl font-bold mt-8 mb-4 text-banana-primary-yellow">3. User Responsibilities</h2>
          <p>As a user, you agree to:</p>
          <ul class="list-disc pl-6 mt-4 space-y-2">
            <li>Provide accurate and complete registration information.</li>
            <li>Maintain the security of your account and password.</li>
            <li>Use the Service in compliance with all applicable laws and regulations.</li>
            <li>Be solely responsible for the content you create and the prompts you provide.</li>
            <li>Respect the intellectual property rights of others.</li>
          </ul>

          <h2 class="text-2xl font-bold mt-8 mb-4 text-banana-primary-yellow">4. Intellectual Property Rights</h2>
          <p>You retain ownership of the prompts you submit and the images and videos you upload for editing. You also own the rights to the videos generated by the Service based on your inputs. By using the Service, you grant MuseSteamer AI a worldwide, non-exclusive, royalty-free license to use, process, and store your content solely for the purpose of providing and improving the Service.</p>

          <h2 class="text-2xl font-bold mt-8 mb-4 text-banana-primary-yellow">5. Prohibited Content and Conduct</h2>
          <p>You may not use the Service to create or share content that is:</p>
          <ul class="list-disc pl-6 mt-4 space-y-2">
            <li>Illegal, harmful, fraudulent, or infringing on the rights of others.</li>
            <li>Hateful, discriminatory, harassing, or violent.</li>
            <li>Sexually explicit or pornographic.</li>
            <li>Intended to deceive, mislead, or spread misinformation.</li>
            <li>In violation of personal privacy.</li>
          </ul>
           <p class="mt-4">Engaging in activities such as reverse-engineering the Service, using automated scripts to generate content excessively, or interfering with the platform's operation is strictly prohibited.</p>

          <h2 class="text-2xl font-bold mt-8 mb-4 text-banana-primary-yellow">6. Subscription and Payment</h2>
          <p>We offer both free and paid subscription plans. Specific features, limits, and pricing are detailed on our pricing page. Subscription fees are billed in advance on a recurring basis and are non-refundable except as required by law.</p>

          <h2 class="text-2xl font-bold mt-8 mb-4 text-banana-primary-yellow">7. Service Modifications and Termination</h2>
          <p>We reserve the right to modify, suspend, or discontinue the Service at any time, with or without notice. We may also terminate or suspend your access to the Service immediately if you breach these Terms.</p>

          <h2 class="text-2xl font-bold mt-8 mb-4 text-banana-primary-yellow">8. Disclaimer of Warranties</h2>
          <p>The Service is provided "as is" and "as available" without any warranties, express or implied. MuseSteamer AI does not warrant that the service will be uninterrupted, error-free, or that the generated content will meet your specific requirements.</p>

          <h2 class="text-2xl font-bold mt-8 mb-4 text-banana-primary-yellow">9. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, MuseSteamer AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Service.</p>

          <h2 class="text-2xl font-bold mt-8 mb-4 text-banana-primary-yellow">10. Contact Information</h2>
          <p>For any questions or concerns regarding these Terms of Service, please contact us at: <a href="mailto:support@musesteamer2.com" class="text-banana-secondary-blue hover:underline">support@musesteamer2.com</a></p>
          <p class="text-sm mt-8">Last updated: August 29,2025</p>
        </section>

      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useSeo } from '~/composables/useSeo';

// @ts-ignore: Nuxt宏函数
definePageMeta({
  name: 'terms-of-service'
})

useSeo({
  title: 'Terms of Service | MuseSteamer AI',
  description: 'Read our terms of service for using MuseSteamer AI - the premier platform for image-to-video generation and AI-powered video editing.'
})
</script>

<style>
/* 移除不必要的全局样式，使用tailwind类名代替 */
</style> 