<template>
  <div
    class="py-16 bg-blue-pale"
    aria-labelledby="normal-vs-ultra-heading"
  >
    <div class="container mx-auto px-4 pt-28 pb-16">
      <article class="max-w-3xl mx-auto">
        <header class="text-center mb-12">
          <h1 class="text-3xl md:text-4xl font-bold  text-center sm:text-5xl bg-gradient-to-r from-[#ec2657] via-[#990066] to-[#ec2657] bg-clip-text text-transparent py-4">Imagen 4.0 vs Ultra | Choosing the Right Image Generation Model</h1>
          <p class="text-lg text-gray-400">A comprehensive guide to Google's latest image generation models, helping you make an informed decision.</p>
        </header>

        <div class="prose prose-invert prose-lg max-w-none mx-auto">
          <p>In June 2024, Google launched Imagen 4, its powerful new image Editor model family, including the high-end Imagen 4 Ultra. This update not only marks a leap in performance but also sets a new standard for image generation accuracy and text rendering. Both versions are now available on our platform. Let's explore their differences.</p>

          <div class="not-prose my-12 flex justify-center items-stretch gap-0">
            <!-- Left Image: Normal -->
            <div class="relative w-1/2">
              <img src="/img/vs/Normal-3.webp" alt="Image generated by Imagen 4 Normal" class="w-full h-full object-cover rounded-l-lg shadow-lg">
              <span class="absolute top-2 right-2 bg-gray-800 bg-opacity-70 text-white text-xs font-semibold px-2 py-1 rounded">Normal</span>
            </div>
            
            <!-- Divider -->
            <div class="w-0.5 bg-white"></div>
          
            <!-- Right Image: Ultra -->
            <div class="relative w-1/2">
              <img src="/img/vs/Ultra-3.webp" alt="Image generated by Imagen 4 Ultra" class="w-full h-full object-cover rounded-r-lg shadow-lg">
              <span class="absolute top-2 left-2 bg-[#ec2657] bg-opacity-80 text-white text-xs font-semibold px-2 py-1 rounded">Ultra</span>
            </div>
          </div>
          <p class="text-center text-sm text-gray-500 mt-3 italic">Prompt: "close-up photo of a woman in her 20s, street photography, movie still, muted orange warm tones"</p>

          <hr class="border-gray-700 my-12" />

          <h2 class="text-3xl font-bold text-[#ec2657] mb-4">Imagen 4 Normal: The All-Rounder for Most Tasks</h2>
          <p>Google positions Imagen 4 as the go-to model for "most tasks." It strikes an excellent balance between cost and performance, making it the ideal choice for everyday creative work, content generation, and rapid prototyping.</p>
          <ul>
            <li><strong>Core Strength</strong>: Cost-effective and capable of handling a wide range of image generation needs.</li>
            <li><strong>Image Quality</strong>: Delivers standard, reliable high-quality images suitable for social media, blog posts, and more.</li>
            <li><strong>Pricing</strong>: <span class="text-[#f3a943] font-semibold">8 credits / image</span>, a competitive price that unleashes creativity without constraints.</li>
          </ul>
          <p>If you need a dependable, efficient, and affordable image generation tool for regular tasks, Imagen 4 Normal is the smart choice.</p>

          <div class="not-prose my-12 flex justify-center items-stretch gap-0">
            <!-- Left Image: Normal -->
            <div class="relative w-1/2">
              <img src="/img/vs/Normal-2.webp" alt="Image generated by Imagen 4 Normal" class="w-full h-full object-cover rounded-l-lg shadow-lg">
              <span class="absolute top-2 right-2 bg-gray-800 bg-opacity-70 text-white text-xs font-semibold px-2 py-1 rounded">Normal</span>
            </div>
            
            <!-- Divider -->
            <div class="w-0.5 bg-white"></div>
          
            <!-- Right Image: Ultra -->
            <div class="relative w-1/2">
              <img src="/img/vs/Ultra-2.webp" alt="Image generated by Imagen 4 Ultra" class="w-full h-full object-cover rounded-r-lg shadow-lg">
              <span class="absolute top-2 left-2 bg-[#ec2657] bg-opacity-80 text-white text-xs font-semibold px-2 py-1 rounded">Ultra</span>
            </div>
          </div>
          <p class="text-center text-sm text-gray-500 mt-3 italic">Prompt: "Front of a vintage travel postcard for Kyoto: iconic pagoda under cherry blossoms, snow-capped mountains in distance, clear blue sky, vibrant colors."</p>

          <hr class="border-gray-700 my-12" />

          <h2 class="text-3xl font-bold text-[#ec2657] mb-4 flex items-center">
            Imagen 4 Ultra: The Premium Choice for Unmatched Precision
            <span class="bg-[#ec2657] text-white text-sm px-3 py-1 rounded-full ml-4">Recommended</span>
          </h2>
          <p>As the flagship offering, Imagen 4 Ultra is built for designers, artists, and professionals who demand the highest level of detail and prompt accuracy. It can interpret and execute complex text instructions more deeply, producing stunning visuals that are highly faithful to the user's intent.</p>
          
          <blockquote>
            <p>Google claims that Imagen 4 Ultra's outputs are preferred over results from top competitors like DALL-E and Midjourney.</p>
          </blockquote>
          
          <ul>
            <li><strong>Core Strength</strong>: Unparalleled ability to follow text prompts, accurately rendering complex scenes and subtle details.</li>
            <li><strong>Image Quality</strong>: Produces top-tier images in terms of detail, style, and artistic flair, suitable for commercial projects and high-quality art.</li>
            <li><strong>Pricing</strong>: <span class="text-[#f3a943] font-semibold">12 credits / image</span>, providing powerful support for your professional needs.</li>
          </ul>

          <div class="not-prose my-12 flex justify-center items-stretch gap-0">
            <!-- Left Image: Normal -->
            <div class="relative w-1/2">
              <img src="/img/vs/Normal-1.webp" alt="Image generated by Imagen 4 Normal" class="w-full h-full object-cover rounded-l-lg shadow-lg">
              <span class="absolute top-2 right-2 bg-gray-800 bg-opacity-70 text-white text-xs font-semibold px-2 py-1 rounded">Normal</span>
            </div>
            
            <!-- Divider -->
            <div class="w-0.5 bg-white"></div>
          
            <!-- Right Image: Ultra -->
            <div class="relative w-1/2">
              <img src="/img/vs/Ultra-1.webp" alt="Image generated by Imagen 4 Ultra" class="w-full h-full object-cover rounded-r-lg shadow-lg">
              <span class="absolute top-2 left-2 bg-[#ec2657] bg-opacity-80 text-white text-xs font-semibold px-2 py-1 rounded">Ultra</span>
            </div>
          </div>
          <p class="text-center text-sm text-gray-500 mt-3 italic">Prompt: "Avant-garde fashion editorial shot: a model in a voluminous, architectural gown standing on a shimmering, alien landscape under a binary sunset, surreal colors, high-concept, cinematic."</p>
           <p>When your project demands precise visual expression, or you want to elevate your creative work to a new level, Imagen 4 Ultra is your indispensable partner.</p>

        </div>
      </article>
                  <!-- Call to Action -->
      <div class="mt-12 text-center">
        <NuxtLink to="/" 
                  class="bg-[#ec2657] text-white px-8 py-3 rounded-full hover:bg-[#990066] transition-colors">
          Start Creating Now
        </NuxtLink>
      </div>
    </div>

  </div>
</template>

<script setup lang="ts">
import { useHead } from '#imports';
useHead({
  title: 'Imagen 4.0 vs Ultra | Best Image Model Choice',
  meta: [
    { name: 'description', content: 'Discover the differences between Google\'s Imagen 4 and Imagen 4 Ultra. Compare performance, pricing, and use cases to choose the best AI model for your needs.' }
  ]
})
</script>

<style>
/* Using prose classes from Tailwind Typography for beautiful article styling */
.prose-invert h2 {
  color: #ec2657;
}

.prose-invert blockquote {
  border-left-color: #ec2657;
  color: #d1d5db;
}

.prose-invert a {
  color: #f3a943;
  transition: color 0.2s;
}

.prose-invert a:hover {
  color: #ec2657;
}

.prose-invert ul > li::before {
  background-color: #f3a943;
}
</style> 