<template>
    <!-- 7. FAQ Section -->
    <section id="faq" class="py-24 px-6">
            <div class="container mx-auto max-w-6xl">
            <div class="text-center mb-16"><h2 class="text-4xl md-text-5xl font-black text-white">Your VibeVoice Questions, Answered</h2><p class="mt-4 text-lg text-[#9CA3AF]">Everything you need to know to get started with the VibeVoice platform.</p></div>
            <div class="grid md:grid-cols-2 gap-8">
                <div class="bg-[#111827] p-6 rounded-xl border border-[#1F2937]">
                    <h3 class="font-bold text-xl text-white">How do I mark multiple speakers in VibeVoice?</h3>
                    <p class="mt-4 text-[#9CA3AF]">Simply start each line of your script with `Speaker: 0`, `Speaker: 1`, and so on. VibeVoice will automatically assign a unique and consistent voice to each speaker ID.</p>
                </div>
                <div class="bg-[#111827] p-6 rounded-xl border border-[#1F2937]">
                    <h3 class="font-bold text-xl text-white">What models are available in VibeVoice?</h3>
                    <p class="mt-4 text-[#9CA3AF]">The free public demo uses our highly efficient 1.5B model for instant results. When you sign up, you'll gain access to even larger, higher-fidelity models for premium quality audio with VibeVoice.</p>
                </div>
                <div class="bg-[#111827] p-6 rounded-xl border border-[#1F2937]">
                    <h3 class="font-bold text-xl text-white">Can I use the VibeVoice generated audio commercially?</h3>
                    <p class="mt-4 text-[#9CA3AF]">Yes, absolutely. The VibeVoice core project is open-source under the MIT License. This gives you the freedom to use audio generated by VibeVoice in your commercial projects, from podcasts to applications.</p>
                </div>
                <div class="bg-[#111827] p-6 rounded-xl border border-[#1F2937]">
                    <h3 class="font-bold text-xl text-white">How do the free VibeVoice bonus credits work?</h3>
                    <p class="mt-4 text-[#9CA3AF]">While you can try VibeVoice without an account, creating a free account rewards you with a large, one-time bonus of credits. These credits unlock longer audio generation, higher priority processing, and access to advanced features.</p>
                </div>
            </div>
        </div>
    </section>
</template>
