<template>
    <!-- 7. FAQ Section -->
    <section id="faq" class="py-24 px-6">
        <div class="container mx-auto max-w-6xl">
            <div class="text-center mb-16">
                <h2 class="text-4xl md-text-5xl font-black text-white">Your VibeVoice Questions, Answered</h2>
                <p class="mt-4 text-lg text-[#9CA3AF]">Everything you need to know to get started with the VibeVoice
                    platform.</p>
            </div>
            <div class="grid md:grid-cols-2 gap-8">
                <div class="bg-[#111827] p-6 rounded-xl border border-[#1F2937]">
                    <h3 class="font-bold text-xl text-white">How do I mark multiple speakers in VibeVoice?</h3>
                    <p class="mt-4 text-[#9CA3AF]">Simply start each line of your script with `Speaker: 0`, `Speaker:
                        1`, and so on. VibeVoice will automatically assign a unique and consistent voice to each speaker
                        ID using VibeVoice.</p>
                </div>
                <div class="bg-[#111827] p-6 rounded-xl border border-[#1F2937]">
                    <h3 class="font-bold text-xl text-white">Is this a one-time payment? Are there any other fees?</h3>
                    <p class="mt-4 text-[#9CA3AF]">Absolutely. This is a one-time payment for the credits themselves. There are no subscription fees, monthly charges, or any hidden costs involved.</p>
                </div>
                <div class="bg-[#111827] p-6 rounded-xl border border-[#1F2937]">
                    <h3 class="font-bold text-xl text-white">Can I use the VibeVoice generated audio commercially?</h3>
                    <p class="mt-4 text-[#9CA3AF]">Yes, absolutely. The VibeVoice core project is open-source under the
                        MIT License. This gives you the freedom to use audio generated by VibeVoice in your commercial
                        projects, from podcasts to applications.</p>
                </div>
                <div class="bg-[#111827] p-6 rounded-xl border border-[#1F2937]">
                    <h3 class="font-bold text-xl text-white">Do the purchased credits expire?</h3>
                    <p class="mt-4 text-[#9CA3AF]">No, they don\'t. All credits you purchase are valid forever. You can use them whenever you like, with no time restrictions.</p>
                </div>
            </div>
        </div>
    </section>
</template>
