<template>
  <section id="faq" style="background-color: var(--bg-color);">
            <div class="container">
                <div class="section-header"><h2 class="gradient-text">Frequently Asked Questions about MuseSteamer</h2></div>
                <div class="faq-container">
                    <details class="faq-item"><summary>What is MuseSteamer AI Video?</summary><div class="faq-content"><p>MuseSteamer AI, developed by Baidu's commercial R&D team for MuseSteamer, is an advanced multimodal AI video generation tool. It uses MuseSteamer AI to turn a single image and a text prompt into a complete, high-quality MuseSteamer AI video with dialogue, sound, and cinematic camera movements.</p></div></details>
                    <details class="faq-item"><summary>What can I create with MuseSteamer AI?</summary><div class="faq-content"><p>With MuseSteamer, you can generate a wide variety of content, including MuseSteamer AI videos with synchronized audio, silent videos, and videos with special effects. MuseSteamer AI Video is ideal for creating cinematic-quality content for commercials, film pre-visualization, social media, and educational purposes.</p></div></details>
                    <details class="faq-item"><summary>How do I use MuseSteamer AI Video?</summary><div class="faq-content"><p>It's a simple, three-step process with MuseSteamer: 1. Upload an image and write a prompt describing your scene and dialogue. 2. Choose the MuseSteamer AI model that best fits your project's needs (e.g., quality, audio). 3. Click "Generate" and your MuseSteamer AI video will be ready to preview and download in minutes.</p></div></details>
                    <details class="faq-item"><summary>What about copyright and commercial use for MuseSteamer AI Video?</summary><div class="faq-content"><p>You must have the legal rights to any source material you upload. Provided you own the source material, you are granted full commercial rights to the MuseSteamer AI videos you generate with MuseSteamer AI. Please refer to our Terms of Service for full details.</p></div></details>
                    <details class="faq-item"><summary>Are there any content restrictions for MuseSteamer?</summary><div class="faq-content"><p>Yes. The creation of content that is illegal, violent, hateful, sexually explicit, or infringes on the rights of others is strictly prohibited when using MuseSteamer. Our platform has content moderation filters in place to enforce this policy and ensure a safe environment.</p></div></details>
                    <details class="faq-item"><summary>How does the payment system work for MuseSteamer?</summary><div class="faq-content"><p>We use a flexible credit-based system at MuseSteamer. You purchase a pack of credits one time, and these credits never expire. This allows you to create MuseSteamer AI video content on your own schedule without the pressure of a recurring monthly subscription.</p></div></details>
                </div>
            </div>
        </section>
</template>
